### ISSUE TITLE
不能外网访问? 我的其他node项目都可以的啊

### ISSUE THREAD

**Issue by lkkchen** [midwayjs/pandora-dashboard#10]
额额，学生党一枚，无论我怎么设置port和host，就是不能外网访问。。我其他node项目各种奇葩端口都有，无论是裸启还是pm2都可以正常外网访问的啊
![image](https://user-images.githubusercontent.com/19872507/37136959-b9d9efbe-22de-11e8-982e-5efef53f01a7.png)
看图也没毛病啊

**Comment by guangwong** [comment]
HOST 你设置的什么，你设置成 0.0.0.0 试试看

**Comment by lkkchen** [comment]
谢谢大佬，啊！ 忘了localhost的本意 0.0.0.0才是王道

**Comment by guangwong** [comment]
嗯... 本地回环就是外面不能访问
