### ISSUE TITLE
关于Actuator模块里面会代理到127.0.0.1:actuatorPort

### ISSUE THREAD

**Issue by stone-jin** [midwayjs/pandora-dashboard#15]
当前网页运行起来后报错。
![image](https://user-images.githubusercontent.com/6525544/44702095-44d63100-aac4-11e8-8958-f5177a50b6e3.png)

查看代码是因为urllib.request(remoteUrl)这个remoteUrl是DASHBOARD_BACKEND，或者127.0.0.1:actuatorPort。

请问这个backend代码在哪里？

**Comment by guangwong** [comment]
嗯，这个是去请求同机的 Pandora 的 Actuator 的 Restful 服务 。也就是这个 http://www.midwayjs.org/pandora/zh-cn/monitor/resource.html

**Comment by stone-jin** [comment]
@guangwong 好的，那我再看一下Pandora.js那个项目的代码
