### ISSUE TITLE
貌似与 Pandora 2.x 不兼容

### ISSUE THREAD

**Issue by vipzhicheng** [midwayjs/pandora-dashboard#18]
恢复到1.x 能启动，但是也没有完全工作正常，是不怎么维护了吗？

**Comment by guangwong** [comment]
是的这个和 2.x 不兼容，主要是 2.x 的监控数据不走 restful server 了，直接每个进程落盘，这个 dashboard 就对不上了。 

2.x 配套了一个集群查看的系统，https://github.com/midwayjs/sandbox-docker 。

**Comment by vipzhicheng** [comment]
嗯嗯，感谢，研究一下。
